theme: jekyll-theme-hacker
show_downloads: true
github:
  zip_url: https://github.com/DeXP/Jackett-Indexers.dlm/archive/refs/heads/master.zip
  tar_url: https://github.com/DeXP/Jackett-Indexers.dlm/archive/refs/heads/master.zip
