theme: jekyll-theme-hacker
show_downloads: true
github:
  zip_url: https://github.com/DeXP/Jackett-Indexers.dlm/tree/master/dlm
  tar_url: https://github.com/DeXP/Jackett-Indexers.dlm/tree/master/dlm
